name: Install and build
on:
  push:
    branches:
      - main
jobs:
  install_and_build:
    runs-on: ubuntu-latest
    name: install
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.13.1"

      - uses: actions/cache@v4
        id: cache-modules
        with:
          path: "**/node_modules"
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - run: npm ci

      - run: npm run build
